version: "3.0"

services:
  rest-api:
    build: .
    volumes:
      - .:/api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: "make run-api"
    ports:
      - 8000:8000
  
     
  